name: Build Chip8 CI

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v4
    - name: build executable
      run: make build-exe
