name: Setup Chip8 Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make configure script executable
      run: chmod +x ./configure
    - name: configure
      run: ./configure
    - name: make
      run: make
