name: Test Chip8 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v4
    - name: run tests
      run: make test
